package orchestrator;

import java.util.HashMap;
import java.util.Map;

public class ContentPipeline {

    public Map<String, Map<String, Object>> runPipeline() {

        Map<String, Object> faqContent = new HashMap<>();
        faqContent.put("q1", "What is this product?");
        faqContent.put("a1", "This is a sample AI-generated product.");

        Map<String, Object> productPageContent = new HashMap<>();
        productPageContent.put("title", "Sample Product");
        productPageContent.put("description", "This product is generated by agents.");

        Map<String, Object> comparisonContent = new HashMap<>();
        comparisonContent.put("competitorA", "Feature set A");
        comparisonContent.put("competitorB", "Feature set B");

        Map<String, Map<String, Object>> output = new HashMap<>();
        output.put("faq", faqContent);
        output.put("productPage", productPageContent);
        output.put("comparisonPage", comparisonContent);

        return output;
    }
}
